version: "3.9"
services:
  fiber-application:
    restart: always
    image: seed-rest-api:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8088:8088
    environment:
      - API_USERID=1
      - API_USERNAME=fiber
      - API_PASSWORD=
      - JWT_SECRET=fiber
    networks:
      - application
    depends_on: 
      - mariadb
    env_file: 
        - .env
    command: ./seed-rest-api

  mariadb:
    image: mariadb:10.6.3
    restart: always
    volumes:
      - ./scripts/migrations.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - 3306
    ports: 
      - 3306:3306
    environment:
      # - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=12345 
      - MYSQL_USER=fiber
      - MYSQL_PASSWORD=12345 
      - MYSQL_DATABASE=fiber_dmca 
    networks:
      - application

networks:
  application: