basePath: /api
definitions:
  user.ResponseHTTP:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  user.User:
    properties:
      address:
        example: Pineapple, Bikini Bottom
        type: string
      created:
        type: integer
      id:
        example: 1
        type: integer
      modified:
        type: integer
      name:
        example: SpongeBob SquarePants
        type: string
      status:
        type: integer
    type: object
info:
  contact:
    email: alexandr.bezverkhniy@gmail.com
    name: Alex Bezverkhniy
  description: This is Seed REST API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API
  version: "1.0"
paths:
  /v1/users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/user.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/user.User'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates new user
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.User'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Creates new user
      tags:
      - user
  /v1/users/{userID}:
    delete:
      consumes:
      - application/json
      description: Deletes user
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Deletes user
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/user.ResponseHTTP'
            - properties:
                data:
                  $ref: '#/definitions/user.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Get user by ID
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Updates user
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: integer
      - description: Update user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Updates user
      tags:
      - user
  /v1/users/status/{status}:
    get:
      consumes:
      - application/json
      description: Gets get all users by status
      parameters:
      - description: User status
        in: path
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/user.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/user.User'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/user.ResponseHTTP'
      summary: Gets get all users by status
      tags:
      - users
swagger: "2.0"
